### PR TITLE
Fixes update button on IE

### PR DESCRIPTION
**Pull request by kchens**

### CODE REVIEW

**Comment by kchens** [comment]
(Kinda) figured out git rebase -i. However, I didn't want to spend up to 30 minutes getting rid of your "peak example" here. So, the last commit here simply comments out .peek once more.

**Comment by TheAlphaNerd** [comment]
just delete peak… it has been removed from develop

**Comment by TheAlphaNerd** [comment]
please reabase interactively and remove both commits referring to peak. I can show you how to do it tomorrow, it should take about 30 seconds.

**Comment by TheAlphaNerd** [comment]
landed as 11e81b0437ce0fa146f009dabdd5f6655c7e7f0b

**Pull request closed without merging**
